name: Deploy Supabase

# Only deploy what's in "main"
on:
  push:
    branches:
      - main
  workflow_dispatch:

# https://supabase.com/docs/guides/functions/cicd-workflow
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: cvdvtzqdkapqvorfgwox

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID
      - run: supabase db push --project-ref $PROJECT_ID
